[{'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestFailure',
     'message': '(<builtins.TestCases testMethod=test_single_element>, \'Traceback (most recent call last):\\n  File "<string>", line 24, in test_single_element\\nAssertionError: 0 is not an instance of <class \\\'float\\\'>\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_custom_list>, \'Traceback (most recent call last):\\n  File "<string>", line 13, in test_custom_list\\n  File "<string>", line 13, in task_func\\n  File "/usr/lib/python3.10/random.py", line 394, in shuffle\\n    x[i], x[j] = x[j], x[i]\\nTypeError: \\\'tuple\\\' object does not support item assignment\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_default_numbers>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in test_default_numbers\\n  File "<string>", line 13, in task_func\\n  File "/usr/lib/python3.10/random.py", line 394, in shuffle\\n    x[i], x[j] = x[j], x[i]\\nTypeError: \\\'tuple\\\' object does not support item assignment\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_empty_list>, \'Traceback (most recent call last):\\n  File "<string>", line 28, in test_empty_list\\n  File "<string>", line 16, in task_func\\nIndexError: tuple index out of range\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_identical_elements>, \'Traceback (most recent call last):\\n  File "<string>", line 33, in test_identical_elements\\n  File "<string>", line 13, in task_func\\n  File "/usr/lib/python3.10/random.py", line 394, in shuffle\\n    x[i], x[j] = x[j], x[i]\\nTypeError: \\\'tuple\\\' object does not support item assignment\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_large_list_with_seed>, \'Traceback (most recent call last):\\n  File "<string>", line 49, in test_large_list_with_seed\\n  File "<string>", line 13, in task_func\\n  File "/usr/lib/python3.10/random.py", line 394, in shuffle\\n    x[i], x[j] = x[j], x[i]\\nTypeError: \\\'tuple\\\' object does not support item assignment\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_mixed_numbers>, \'Traceback (most recent call last):\\n  File "<string>", line 38, in test_mixed_numbers\\n  File "<string>", line 13, in task_func\\n  File "/usr/lib/python3.10/random.py", line 394, in shuffle\\n    x[i], x[j] = x[j], x[i]\\nTypeError: \\\'tuple\\\' object does not support item assignment\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_negative_numbers>, \'Traceback (most recent call last):\\n  File "<string>", line 18, in test_negative_numbers\\n  File "<string>", line 13, in task_func\\n  File "/usr/lib/python3.10/random.py", line 394, in shuffle\\n    x[i], x[j] = x[j], x[i]\\nTypeError: \\\'tuple\\\' object does not support item assignment\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_random_behavior>, \'Traceback (most recent call last):\\n  File "<string>", line 54, in test_random_behavior\\n  File "<string>", line 13, in task_func\\n  File "/usr/lib/python3.10/random.py", line 394, in shuffle\\n    x[i], x[j] = x[j], x[i]\\nTypeError: \\\'tuple\\\' object does not support item assignment\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_specific_value_with_seed>, \'Traceback (most recent call last):\\n  File "<string>", line 44, in test_specific_value_with_seed\\n  File "<string>", line 13, in task_func\\n  File "/usr/lib/python3.10/random.py", line 394, in shuffle\\n    x[i], x[j] = x[j], x[i]\\nTypeError: \\\'tuple\\\' object does not support item assignment\\n\')'}]}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_generated_string_properties>, \'Traceback (most recent call last):\\n  File "<string>", line 6, in setUp\\nNameError: name \\\'string\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_negative_length>, \'Traceback (most recent call last):\\n  File "<string>", line 6, in setUp\\nNameError: name \\\'string\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_zero_length>, \'Traceback (most recent call last):\\n  File "<string>", line 6, in setUp\\nNameError: name \\\'string\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0.6,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestFailure',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "<string>", line 19, in test_case_3\\nAssertionError: False is not true : All values of the dictionary should be lists of integers.\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_4>, \'Traceback (most recent call last):\\n  File "<string>", line 23, in test_case_4\\n  File "<string>", line 23, in <listcomp>\\nNameError: name \\\'statistics\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 1.0,
  'executability': True,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 1.0,
  'executability': True,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_custom_letters>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'random\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_default_letters>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'random\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_empty_letters>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'random\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_known_values>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'random\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_uniform_values>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'random\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0.4,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestFailure',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 22, in test_case_2\\nAssertionError: None != \\\'/mock_dir/access.log.1\\\'\\n\')'},
    {'type': 'TestFailure',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 31, in test_case_3\\nAssertionError: None != \\\'/mock_dir/access.log.123\\\'\\n\')'},
    {'type': 'TestFailure',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 48, in test_case_5\\nAssertionError: None != \\\'/var/log/access.log.999\\\'\\n\')'}]}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_1>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_4>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_6>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_7>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'FunctionError',
     'message': 'task_func is not defined in the generated code.'}],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'FunctionError',
     'message': 'task_func is not defined in the generated code.'}],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_1>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 10, in test_case_1\\n  File "<string>", line 7, in task_func\\nTypeError: int() argument must be a string, a bytes-like object or a real number, not \\\'tuple\\\'\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 20, in test_case_2\\n  File "<string>", line 7, in task_func\\nTypeError: int() argument must be a string, a bytes-like object or a real number, not \\\'tuple\\\'\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 28, in test_case_3\\n  File "<string>", line 7, in task_func\\nTypeError: int() argument must be a string, a bytes-like object or a real number, not \\\'tuple\\\'\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_4>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 36, in test_case_4\\n  File "<string>", line 7, in task_func\\nTypeError: int() argument must be a string, a bytes-like object or a real number, not \\\'tuple\\\'\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 44, in test_case_5\\n  File "<string>", line 7, in task_func\\nTypeError: int() argument must be a string, a bytes-like object or a real number, not \\\'tuple\\\'\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_empty_input>, \'Traceback (most recent call last):\\n  File "<string>", line 51, in test_empty_input\\nNameError: name \\\'statistics\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_1>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 9, in test_case_1\\nValueError: not enough values to unpack (expected 3, got 2)\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 18, in test_case_2\\nValueError: not enough values to unpack (expected 3, got 2)\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 27, in test_case_3\\nValueError: not enough values to unpack (expected 3, got 2)\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_4>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 36, in test_case_4\\nValueError: not enough values to unpack (expected 3, got 2)\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 45, in test_case_5\\nValueError: not enough values to unpack (expected 3, got 2)\\n\')'}]}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'FunctionError',
     'message': 'task_func is not defined in the generated code.'}],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_1>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_4>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [{'type': 'SyntaxError',
     'message': 'unterminated string literal (detected at line 2) (<string>, line 2)'}],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_command_failure_with_specific_exit_code>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_empty_csv_file>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_file_not_found>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_invalid_command>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_mixed_commands>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_successful_command_execution>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_backup_creation_and_log_file_deletion>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_handle_non_existing_directory>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_no_log_files_to_backup>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_non_log_files_remain>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [{'type': 'SyntaxError',
     'message': 'invalid syntax (<string>, line 1)'}],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_invalid_file>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_large_csv>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_medium_csv>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_non_csv_file>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_small_csv>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_empty_directory>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_exclusion_of_subdirectories>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_file_integrity_in_zip>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_multiple_files_zip>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_non_existent_directory>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_single_file_zip>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in setUp\\nNameError: name \\\'tempfile\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [{'type': 'SyntaxError',
     'message': 'unterminated string literal (detected at line 21) (<string>, line 21)'}],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'ExecutionError',
     'message': "name 'python' is not defined"}],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_1>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'random\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'random\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'random\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_4>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'random\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'random\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_with_non_integers>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'random\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_empty_first_list>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'random\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_imbalanced_lists>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in setUp\\nNameError: name \\\'random\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'FunctionError',
     'message': 'task_func is not defined in the generated code.'}],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'ExecutionError',
     'message': "No module named 'Crypto'"}],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [{'type': 'SyntaxError',
     'message': 'invalid syntax (<string>, line 16)'}],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'ExecutionError',
     'message': "name 'python' is not defined"}],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_task_func_basic>, \'Traceback (most recent call last):\\n  File "<string>", line 11, in test_task_func_basic\\nNameError: name \\\'json\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_task_func_empty>, \'Traceback (most recent call last):\\n  File "<string>", line 22, in test_task_func_empty\\nNameError: name \\\'json\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_task_func_mixed>, \'Traceback (most recent call last):\\n  File "<string>", line 52, in test_task_func_mixed\\nNameError: name \\\'json\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_task_func_nested>, \'Traceback (most recent call last):\\n  File "<string>", line 31, in test_task_func_nested\\nNameError: name \\\'json\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_task_func_numeric>, \'Traceback (most recent call last):\\n  File "<string>", line 41, in test_task_func_numeric\\nNameError: name \\\'json\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [{'type': 'SyntaxError',
     'message': 'f-string: invalid syntax (<string>, line 16)'}],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_output_is_string_and_valid_base64>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in test_output_is_string_and_valid_base64\\nNameError: name \\\'np\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_varied_data_sets>, \'Traceback (most recent call last):\\n  File "<string>", line 28, in test_varied_data_sets\\nNameError: name \\\'np\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_with_mocked_scaler>, \'Traceback (most recent call last):\\n  File "<string>", line 19, in test_with_mocked_scaler\\nNameError: name \\\'np\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [{'type': 'SyntaxError',
     'message': 'invalid syntax (<string>, line 6)'}],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0.4,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_1>, \'Traceback (most recent call last):\\n  File "<string>", line 26, in test_case_1\\nNameError: name \\\'plt\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "<string>", line 32, in test_case_2\\nNameError: name \\\'plt\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "<string>", line 55, in test_case_5\\nNameError: name \\\'plt\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_empty_tag>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 62, in test_empty_tag\\nNameError: name \\\'Mock\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_h1_tag_found>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 20, in test_h1_tag_found\\nNameError: name \\\'Mock\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_invalid_url_handling>, \'Traceback (most recent call last):\\n  File "<string>", line 36, in test_invalid_url_handling\\nNameError: name \\\'requests\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_malformed_html>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 42, in test_malformed_html\\nNameError: name \\\'Mock\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_multiple_matching_tags>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 53, in test_multiple_matching_tags\\nNameError: name \\\'Mock\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_nonexistent_tag>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 29, in test_nonexistent_tag\\nNameError: name \\\'Mock\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_title_tag_found>, \'Traceback (most recent call last):\\n  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched\\n    return func(*newargs, **newkeywargs)\\n  File "<string>", line 11, in test_title_tag_found\\nNameError: name \\\'Mock\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_1>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in test_case_1\\nNameError: name \\\'np\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "<string>", line 17, in test_case_2\\nNameError: name \\\'np\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "<string>", line 24, in test_case_3\\nNameError: name \\\'np\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_4>, \'Traceback (most recent call last):\\n  File "<string>", line 31, in test_case_4\\nNameError: name \\\'np\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "<string>", line 38, in test_case_5\\nNameError: name \\\'np\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestFailure',
     'message': '(<builtins.TestCases testMethod=test_case_4>, \'Traceback (most recent call last):\\n  File "<string>", line 22, in test_case_4\\nAssertionError: ValueError not raised\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_1>, \'Traceback (most recent call last):\\n  File "<string>", line 9, in test_case_1\\nNameError: name \\\'WordCloud\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "<string>", line 14, in test_case_2\\nNameError: name \\\'WordCloud\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "<string>", line 19, in test_case_3\\nNameError: name \\\'WordCloud\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "<string>", line 31, in test_case_5\\nNameError: name \\\'WordCloud\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_1>, \'Traceback (most recent call last):\\n  File "<string>", line 6, in test_case_1\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "<string>", line 10, in test_case_2\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "<string>", line 15, in test_case_3\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_4>, \'Traceback (most recent call last):\\n  File "<string>", line 22, in test_case_4\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "<string>", line 30, in test_case_5\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_7>, \'Traceback (most recent call last):\\n  File "<string>", line 35, in test_case_7\\nNameError: name \\\'pd\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'ExecutionError',
     'message': 'Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).'}],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [{'type': 'SyntaxError',
     'message': 'invalid syntax (<string>, line 43)'}],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_1>, \'Traceback (most recent call last):\\n  File "<string>", line 6, in test_case_1\\nNameError: name \\\'np\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "<string>", line 20, in test_case_2\\nNameError: name \\\'np\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "<string>", line 34, in test_case_3\\nNameError: name \\\'np\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_4>, \'Traceback (most recent call last):\\n  File "<string>", line 48, in test_case_4\\nNameError: name \\\'np\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "<string>", line 78, in test_case_5\\nNameError: name \\\'np\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_1>, \'Traceback (most recent call last):\\n  File "<string>", line 5, in test_case_1\\nNameError: name \\\'np\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in test_case_2\\nNameError: name \\\'np\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "<string>", line 11, in test_case_3\\nNameError: name \\\'np\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_4>, \'Traceback (most recent call last):\\n  File "<string>", line 14, in test_case_4\\nNameError: name \\\'np\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "<string>", line 21, in test_case_5\\nNameError: name \\\'np\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'FunctionError',
     'message': 'task_func is not defined in the generated code.'}],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_1>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_4>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "<string>", line 8, in setUp\\nNameError: name \\\'os\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'ExecutionError',
     'message': "'PCA' object has no attribute 'means_'"}],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'ExecutionError',
     'message': "data type 'count' not understood"}],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'FunctionError',
     'message': 'task_func is not defined in the generated code.'}],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_1>, \'Traceback (most recent call last):\\n  File "<string>", line 5, in test_case_1\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "<string>", line 15, in test_case_2\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "<string>", line 31, in test_case_3\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_4>, \'Traceback (most recent call last):\\n  File "<string>", line 45, in test_case_4\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "<string>", line 59, in test_case_5\\nNameError: name \\\'pd\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0.0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [],
   'Optimization Issues': [],
   'Test Case Failures': [{'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_1>, \'Traceback (most recent call last):\\n  File "<string>", line 7, in test_case_1\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_2>, \'Traceback (most recent call last):\\n  File "<string>", line 18, in test_case_2\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_3>, \'Traceback (most recent call last):\\n  File "<string>", line 29, in test_case_3\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_4>, \'Traceback (most recent call last):\\n  File "<string>", line 46, in test_case_4\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_5>, \'Traceback (most recent call last):\\n  File "<string>", line 56, in test_case_5\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_6>, \'Traceback (most recent call last):\\n  File "<string>", line 66, in test_case_6\\nNameError: name \\\'pd\\\' is not defined\\n\')'},
    {'type': 'TestError',
     'message': '(<builtins.TestCases testMethod=test_case_7>, \'Traceback (most recent call last):\\n  File "<string>", line 77, in test_case_7\\nNameError: name \\\'pd\\\' is not defined\\n\')'}]}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'ExecutionError',
     'message': "name 'python' is not defined"}],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'FunctionError',
     'message': 'task_func is not defined in the generated code.'}],
   'Optimization Issues': [],
   'Test Case Failures': []}},
 {'pass_ratio': 0,
  'executability': False,
  'errors': {'Syntax Errors': [],
   'Logical Errors': [{'type': 'ExecutionError',
     'message': "Failed to convert value(s) to axis units: array(['2022-07-16T17:53:20.000000000', '2022-07-16T19:00:00.000000000',\n       '2022-07-16T20:06:40.000000000', '2022-07-16T21:13:20.000000000',\n       '2022-07-16T22:20:00.000000000'], dtype='datetime64[ns]')"}],
   'Optimization Issues': [],
   'Test Case Failures': []}}]